# a mybinder.org-ready environment for demoing chaldene
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   conda env update --file binder/environment.yml
#   conda activate chaldene-demo
#
name: chaldene-demo

channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - python >=3.10,<3.11.0a0
  - jupyterlab >=4.0.0,<5
  # labextension build dependencies
  - nodejs >=18,<19
  - pip
  - wheel
  - pip:
      - git+https://github.com/c3di/im2im.git
      - numpy
      - pillow
      - pandas
      - scikit-image
      - scipy
      - comm
      - opencv-python
      - matplotlib
      - napari-segment-blobs-and-things-with-membranes
  # additional packages for demos
  # - ipywidgets
